/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Desktop;
import java.net.URL;

/**
 *
 * @author dbuu
 */
public class aboutPappu extends javax.swing.JFrame {

    /**
     * Creates new form aboutPappu
     */
    public aboutPappu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel1 = new javax.swing.JPanel();
        pic = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        intro1 = new javax.swing.JLabel();
        intro2 = new javax.swing.JLabel();
        intro3 = new javax.swing.JLabel();
        intro4 = new javax.swing.JLabel();
        intro5 = new javax.swing.JLabel();
        projecttitle = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        FbButton = new javax.swing.JButton();
        InstaButton = new javax.swing.JButton();
        LinkedInButton = new javax.swing.JButton();
        GithubButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgPanel1.setBackground(new java.awt.Color(255, 255, 255));
        bgPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 0), 2, true));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/icon/about .png"))); // NOI18N

        HomeButton.setBackground(new java.awt.Color(96, 202, 207));
        HomeButton.setText("Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        name.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        name.setText("Vijay Patel");
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nameMouseEntered(evt);
            }
        });

        intro1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        intro1.setText("Student MCA at Dev Bhoomi Uttarakhand Unversity.");

        intro2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        intro2.setText(" professional skilled in C, C++, Java, SQL, HTML,");

        intro3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        intro3.setText("independent and passionate about solving problems,");

        intro4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        intro4.setText("CSS and NetBeans and VSCode IDE. I am hard-working,");

        intro5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        intro5.setText(" working in a team.");

        projecttitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        projecttitle.setText("Project Name : Password Manager");

        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email.setText("Email : vk86736@gmail.com");

        FbButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/icon/facebook.png"))); // NOI18N
        FbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FbButtonActionPerformed(evt);
            }
        });

        InstaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/icon/instagram.png"))); // NOI18N
        InstaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstaButtonActionPerformed(evt);
            }
        });

        LinkedInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/icon/linkedin.png"))); // NOI18N
        LinkedInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LinkedInButtonActionPerformed(evt);
            }
        });

        GithubButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/icon/github.png"))); // NOI18N
        GithubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GithubButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgPanel1Layout = new javax.swing.GroupLayout(bgPanel1);
        bgPanel1.setLayout(bgPanel1Layout);
        bgPanel1Layout.setHorizontalGroup(
            bgPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanel1Layout.createSequentialGroup()
                .addGroup(bgPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(FbButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InstaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LinkedInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GithubButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(pic))
                    .addGroup(bgPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(intro2))
                    .addGroup(bgPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(bgPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(intro4)
                            .addGroup(bgPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(bgPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(projecttitle)
                                    .addComponent(intro3)))))
                    .addGroup(bgPanel1Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(intro5))
                    .addGroup(bgPanel1Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(email))
                    .addGroup(bgPanel1Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(HomeButton))
                    .addGroup(bgPanel1Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(name))
                    .addGroup(bgPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(intro1)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        bgPanel1Layout.setVerticalGroup(
            bgPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pic)
                .addGap(18, 18, 18)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(intro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intro2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intro4)
                .addGap(4, 4, 4)
                .addComponent(intro3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intro5)
                .addGap(18, 18, 18)
                .addComponent(projecttitle)
                .addGap(14, 14, 14)
                .addGroup(bgPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LinkedInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GithubButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FbButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InstaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
        MainFrame m = new MainFrame();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_nameMouseEntered

    private void FbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FbButtonActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.facebook.com/pgl.vijay").toURI());
    }//GEN-LAST:event_FbButtonActionPerformed
    catch(Exception e){}
    
    }
    private void InstaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstaButtonActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.instagram.com/harshit_koder").toURI());
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_InstaButtonActionPerformed

    private void LinkedInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LinkedInButtonActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.linkedin.com/in/vijay-kumar-patel-1853b31b5").toURI());
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_LinkedInButtonActionPerformed

    private void GithubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GithubButtonActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.github.com/vijay320").toURI());
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_GithubButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aboutPappu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aboutPappu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aboutPappu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aboutPappu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aboutPappu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FbButton;
    private javax.swing.JButton GithubButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton InstaButton;
    private javax.swing.JButton LinkedInButton;
    private javax.swing.JPanel bgPanel1;
    private javax.swing.JLabel email;
    private javax.swing.JLabel intro1;
    private javax.swing.JLabel intro2;
    private javax.swing.JLabel intro3;
    private javax.swing.JLabel intro4;
    private javax.swing.JLabel intro5;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel projecttitle;
    // End of variables declaration//GEN-END:variables
}
